-- ==========================================================================
-- REIS IA [HUB] — Hub Knowledge Base
-- Central repository for all form responses, research, feedback, surveys
-- Run this in Supabase SQL Editor
-- ==========================================================================

create table public.hub_knowledge (
  id uuid primary key default gen_random_uuid(),

  -- Who created/submitted this entry
  user_id uuid references public.profiles(id),
  user_name text,
  user_email text,

  -- What type of data
  category text not null check (category in (
    'form_response',      -- Branding form submissions
    'checkpoint_feedback', -- Journey checkpoint feedback
    'survey_response',     -- Any survey/questionnaire
    'research',           -- Market research, competitor analysis
    'meeting_notes',      -- Call transcriptions, meeting summaries
    'client_data',        -- Client diagnostics, proposals
    'agent_output',       -- Outputs generated by agents
    'general'             -- Anything else
  )),

  -- Content
  title text not null,
  summary text,                    -- Short summary (1-2 lines)
  content text not null,           -- Full content (can be long)

  -- Metadata
  source text,                     -- Where it came from (form name, agent name, call, etc)
  tags text[] default '{}',        -- Searchable tags
  metadata jsonb default '{}',     -- Any extra structured data

  -- Linked entities (optional)
  journey_id uuid,                 -- If related to a journey
  project_id uuid,                 -- If related to a project

  -- Status
  status text not null default 'active' check (status in ('active', 'archived')),

  -- Timestamps
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Indexes
create index idx_hk_user on public.hub_knowledge(user_id);
create index idx_hk_category on public.hub_knowledge(category);
create index idx_hk_created on public.hub_knowledge(created_at desc);
create index idx_hk_tags on public.hub_knowledge using gin(tags);

-- RLS
alter table public.hub_knowledge enable row level security;
create policy hk_admin_all on public.hub_knowledge for all using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);
create policy hk_own_read on public.hub_knowledge for select using (user_id = auth.uid());
create policy hk_own_insert on public.hub_knowledge for insert with check (user_id = auth.uid());

-- Updated at trigger
create trigger update_hub_knowledge_updated_at
  before update on public.hub_knowledge
  for each row execute procedure public.update_updated_at();
